import main_function as mn
import csv
import pandas as pd
df=pd.read_excel('X-XII Student List.xlsx',sheet_name=[0])[0]
df.sort_values(by=['Gender','Class','Section','Name'],inplace=True)
df=mn.genrate_id(df)
df=mn.genrate_roll_no(df)
girls_df=pd.DataFrame(df[df["Gender"]=='F'])
girls_df.sort_values(by=['Gender','Class','Section','Name'],inplace=True)
classes=girls_df.groupby(by=['Class']).count().PR.to_dict()
S = list(classes.values())
m= mn.findMinAbsDiff(S, len(S) - 1)
f=mn.findsubsets(S)
x,y=mn.break_list(f,m,sum(S))
class_list1,class_list2=mn.get_class_list(x,y,classes)
group1=mn.assign_group_to_class(girls_df,class_list1)
group2=mn.assign_group_to_class(girls_df,class_list2,2)
n_seat=int(input("Enter Number Of Seats In a Room: "))
n_row=int(input("Enter Number Of Rows In a Room: "))
print("Waiting!!!!!!!")
alt_df1=mn.arrange_alternate(group1,group2,n_seat)
#alt_df1.to_csv('room_arrange girls.csv')
boy_df=pd.DataFrame(df[df["Gender"]=='M'])
boy_df.sort_values(by=['Gender','Class','Section','Name'],inplace=True)
classes=boy_df.groupby(by=['Class']).count().PR.to_dict()
S = list(classes.values())
min_diff= mn.findMinAbsDiff(S, len(S) - 1)
class_sub_set=mn.findsubsets(S)
x,y=mn.break_list(class_sub_set,min_diff,sum(S))
class_list3,class_list4=mn.get_class_list(x,y,classes)
group3=mn.assign_group_to_class(boy_df,class_list3)
group4=mn.assign_group_to_class(boy_df,class_list4,2)
alt_df2=mn.arrange_alternate(group3,group4,n_seat)
#alt_df2.to_csv('boys.csv')
alt_df=pd.concat([alt_df1,alt_df2])
alt_df=mn.room_alotment(alt_df,n_seat)
alt_df.sort_values(by=['Room','Class','Section','Name'],inplace=True)
alt_df.to_csv('room_arrangement.csv',index=False)
mn.genrate_attendance_sheet(alt_df,[],','.join(classes.keys()))
mn.genrate_seat_plan(alt_df,n_seat,n_row,','.join(classes.keys()))
print("Plan Generated successfully") 
